/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { MiMCSponge, MiMCSpongeInterface } from "../../src/MiMCSponge";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_left",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_right",
        type: "uint256",
      },
    ],
    name: "MiMCHash",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234610234575f80557f0fbe43c36a80e36d7c7c584d4f8f3759fb51f0d66065d8a227b688d12488c5d46001557f0b1be1e55d1138dcfc4eeee6618b1b7cde5c4a262e83139555673f5751efc1c96002557f27c0849dba2643077c13eb42ffb97663cdcecd669bf10f756be30bab71b86cf86003557f2bf76744736132e5c68f7dfdd5b792681d415098554fd8280f00d11b172b80d26004557f02aef041c0700b1b4b2c4629195a5a3c737b1ea990e32486c9e2d748cec585676005557f282767ed3103cd92e2b5593b56115d072f5dc7a45ad58962b692980a41c7fab66006557f085ff8f3e28f159cef57989c88bb8b3f91060bdd68522305d93cd30ab8f03ef36007557f120ed97b7792f9eb455f42029e68268193cd960d8c637c28fb497d95ea8744e36008557f18d343a251144f28d6b6b49372a8e078f87de959b85d4d262bb29475c18de9ff6009557f0db86182b7963c4a1a6bb2e4ddce9c998488c73195d5a27675f14777e727acf2600a557f18172a0b610b638b58fd06ad4702e4b8f03294eba526db4d3dbd1a4ba8a12562600b557f0a35b77d2364c525bfc79b188669438cc22e318c62df7e206bed00c9c0de28a0600c557f2d29440068d952b1107cff4aee94643fe8ace954e875f67f6ab296b259ff796c600d557f024b619541491cad1c7bb44a48a1a83dfe7243ab7c002bf2a04628ce11197efa600e557f0d59aa7de68556abc0a25a3b199fe3aa2b756a23fd53e4fe8027e52926df389c600f5560e390816102398239f35b5f80fdfe608060405260043610156010575f80fd5b5f3560e01c636aafaa16146022575f80fd5b3460a957604036600319011260a9576004356024355f805b60dc821015609e57815490608a577f30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001805f8160019488080893818086800995815f9780090990089101909291603a565b634e487b7160e01b5f52601260045260245ffd5b602084604051908152f35b5f80fdfea2646970667358221220c75591150ac4d80bbb008ff64ec4ce7fc3d12584e8f1617caea99615b2581a7164736f6c634300081e0033";

type MiMCSpongeConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MiMCSpongeConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MiMCSponge__factory extends ContractFactory {
  constructor(...args: MiMCSpongeConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MiMCSponge & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MiMCSponge__factory {
    return super.connect(runner) as MiMCSponge__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MiMCSpongeInterface {
    return new Interface(_abi) as MiMCSpongeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MiMCSponge {
    return new Contract(address, _abi, runner) as unknown as MiMCSponge;
  }
}
