/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { Verifier, VerifierInterface } from "../../src/Verifier";

const _abi = [
  {
    inputs: [],
    name: "disableMockMode",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "mockMode",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[8]",
        name: "proof",
        type: "uint256[8]",
      },
      {
        internalType: "uint256[6]",
        name: "input",
        type: "uint256[6]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60806040525f805460ff19166001179055348015601a575f5ffd5b506101a7806100285f395ff3fe608060405234801561000f575f5ffd5b506004361061003f575f3560e01c8063751222c91461004357806391027655146100635780639cb2865814610073575b5f5ffd5b5f5461004f9060ff1681565b604051901515815260200160405180910390f35b6100715f805460ff19169055565b005b61004f61008136600461011c565b5f805460ff1615610113575f5b60088110156100c5578381600881106100a9576100a961015d565b60200201355f036100bd575f915050610116565b60010161008e565b5081355f036100d557505f610116565b60208201355f036100e757505f610116565b60408201355f036100f957505f610116565b60a08201355f0361010b57505f610116565b506001610116565b505f5b92915050565b5f5f6101c0838503121561012e575f5ffd5b61010083018481111561013f575f5ffd5b839250846101c085011115610152575f5ffd5b809150509250929050565b634e487b7160e01b5f52603260045260245ffdfea2646970667358221220b9d9a7fe7d7b9fd26670af89ae4a0998c461a430c72f016deb7f115764adc15364736f6c634300081e0033";

type VerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: VerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Verifier__factory extends ContractFactory {
  constructor(...args: VerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Verifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Verifier__factory {
    return super.connect(runner) as Verifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): VerifierInterface {
    return new Interface(_abi) as VerifierInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Verifier {
    return new Contract(address, _abi, runner) as unknown as Verifier;
  }
}
