/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  HasherAdapter,
  HasherAdapterInterface,
} from "../../../src/HasherAdapter.sol/HasherAdapter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_mimcSponge",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "left",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "right",
        type: "uint256",
      },
    ],
    name: "MiMCSponge",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "input",
        type: "uint256",
      },
    ],
    name: "hash",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "mimcSponge",
    outputs: [
      {
        internalType: "contract IMiMCSponge",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a034606e57601f61036e38819003918201601f19168301916001600160401b03831184841017607257808492602094604052833981010312606e57516001600160a01b03811690819003606e576080526040516102e790816100878239608051818181607301526101b90152f35b5f80fd5b634e487b7160e01b5f52604160045260245ffdfe6080806040526004361015610012575f80fd5b5f3560e01c908163b189fd4c146101e857508063e7472b91146101a45763f47d33b51461003d575f80fd5b346101a05760403660031901126101a05760408051633f1a118760e01b815260048035908201525f6024820181905260448201527f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03169181606481855afa91821561014b575f915f93610156575b5060646040927f30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f00000019284519586948593633f1a118760e01b855260243508600484015260248301525f60448301525afa801561014b576020915f9161011b575b50604051908152f35b61013d915060403d604011610144575b6101358183610265565b81019061029b565b505f610112565b503d61012b565b6040513d5f823e3d90fd5b7f30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f000000191935060409250610196606491843d8611610144576101358183610265565b94925092506100b3565b5f80fd5b346101a0575f3660031901126101a0576040517f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b346101a05760203660031901126101a05760043563f47d33b560e01b82528060048301526024820152602081604481305afa801561014b575f90610232575b602090604051908152f35b506020813d60201161025d575b8161024c60209383610265565b810103126101a05760209051610227565b3d915061023f565b90601f8019910116810190811067ffffffffffffffff82111761028757604052565b634e487b7160e01b5f52604160045260245ffd5b91908260409103126101a057602082519201519056fea2646970667358221220e2242296e42083a862d556556faec9c330dc24de07aaf82646b0b403e0b7dc6a64736f6c634300081e0033";

type HasherAdapterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: HasherAdapterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class HasherAdapter__factory extends ContractFactory {
  constructor(...args: HasherAdapterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _mimcSponge: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_mimcSponge, overrides || {});
  }
  override deploy(
    _mimcSponge: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_mimcSponge, overrides || {}) as Promise<
      HasherAdapter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): HasherAdapter__factory {
    return super.connect(runner) as HasherAdapter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HasherAdapterInterface {
    return new Interface(_abi) as HasherAdapterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): HasherAdapter {
    return new Contract(address, _abi, runner) as unknown as HasherAdapter;
  }
}
