/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMiMCSponge,
  IMiMCSpongeInterface,
} from "../../../src/HasherAdapter.sol/IMiMCSponge";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "xL_in",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "xR_in",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "k",
        type: "uint256",
      },
    ],
    name: "MiMCSponge",
    outputs: [
      {
        internalType: "uint256",
        name: "xL",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "xR",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class IMiMCSponge__factory {
  static readonly abi = _abi;
  static createInterface(): IMiMCSpongeInterface {
    return new Interface(_abi) as IMiMCSpongeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMiMCSponge {
    return new Contract(address, _abi, runner) as unknown as IMiMCSponge;
  }
}
