/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DogeRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addPool"
      | "depositDoge"
      | "owner"
      | "removePool"
      | "transferOwnership"
      | "validPools"
      | "wdoge"
      | "withdrawDoge"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositDoge"
      | "PoolAdded"
      | "PoolRemoved"
      | "WithdrawDoge"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositDoge",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removePool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validPools",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "wdoge", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawDoge",
    values: [
      AddressLike,
      BigNumberish[],
      BytesLike,
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "addPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositDoge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validPools", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wdoge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawDoge",
    data: BytesLike
  ): Result;
}

export namespace DepositDogeEvent {
  export type InputTuple = [
    pool: AddressLike,
    commitment: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [pool: string, commitment: string, amount: bigint];
  export interface OutputObject {
    pool: string;
    commitment: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolAddedEvent {
  export type InputTuple = [pool: AddressLike];
  export type OutputTuple = [pool: string];
  export interface OutputObject {
    pool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolRemovedEvent {
  export type InputTuple = [pool: AddressLike];
  export type OutputTuple = [pool: string];
  export interface OutputObject {
    pool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawDogeEvent {
  export type InputTuple = [
    pool: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [pool: string, recipient: string, amount: bigint];
  export interface OutputObject {
    pool: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DogeRouter extends BaseContract {
  connect(runner?: ContractRunner | null): DogeRouter;
  waitForDeployment(): Promise<this>;

  interface: DogeRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addPool: TypedContractMethod<[pool: AddressLike], [void], "nonpayable">;

  depositDoge: TypedContractMethod<
    [pool: AddressLike, commitment: BytesLike],
    [void],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removePool: TypedContractMethod<[pool: AddressLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  validPools: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  wdoge: TypedContractMethod<[], [string], "view">;

  withdrawDoge: TypedContractMethod<
    [
      pool: AddressLike,
      proof: BigNumberish[],
      root: BytesLike,
      nullifierHash: BytesLike,
      recipient: AddressLike,
      relayer: AddressLike,
      fee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addPool"
  ): TypedContractMethod<[pool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositDoge"
  ): TypedContractMethod<
    [pool: AddressLike, commitment: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removePool"
  ): TypedContractMethod<[pool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validPools"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "wdoge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawDoge"
  ): TypedContractMethod<
    [
      pool: AddressLike,
      proof: BigNumberish[],
      root: BytesLike,
      nullifierHash: BytesLike,
      recipient: AddressLike,
      relayer: AddressLike,
      fee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DepositDoge"
  ): TypedContractEvent<
    DepositDogeEvent.InputTuple,
    DepositDogeEvent.OutputTuple,
    DepositDogeEvent.OutputObject
  >;
  getEvent(
    key: "PoolAdded"
  ): TypedContractEvent<
    PoolAddedEvent.InputTuple,
    PoolAddedEvent.OutputTuple,
    PoolAddedEvent.OutputObject
  >;
  getEvent(
    key: "PoolRemoved"
  ): TypedContractEvent<
    PoolRemovedEvent.InputTuple,
    PoolRemovedEvent.OutputTuple,
    PoolRemovedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawDoge"
  ): TypedContractEvent<
    WithdrawDogeEvent.InputTuple,
    WithdrawDogeEvent.OutputTuple,
    WithdrawDogeEvent.OutputObject
  >;

  filters: {
    "DepositDoge(address,bytes32,uint256)": TypedContractEvent<
      DepositDogeEvent.InputTuple,
      DepositDogeEvent.OutputTuple,
      DepositDogeEvent.OutputObject
    >;
    DepositDoge: TypedContractEvent<
      DepositDogeEvent.InputTuple,
      DepositDogeEvent.OutputTuple,
      DepositDogeEvent.OutputObject
    >;

    "PoolAdded(address)": TypedContractEvent<
      PoolAddedEvent.InputTuple,
      PoolAddedEvent.OutputTuple,
      PoolAddedEvent.OutputObject
    >;
    PoolAdded: TypedContractEvent<
      PoolAddedEvent.InputTuple,
      PoolAddedEvent.OutputTuple,
      PoolAddedEvent.OutputObject
    >;

    "PoolRemoved(address)": TypedContractEvent<
      PoolRemovedEvent.InputTuple,
      PoolRemovedEvent.OutputTuple,
      PoolRemovedEvent.OutputObject
    >;
    PoolRemoved: TypedContractEvent<
      PoolRemovedEvent.InputTuple,
      PoolRemovedEvent.OutputTuple,
      PoolRemovedEvent.OutputObject
    >;

    "WithdrawDoge(address,address,uint256)": TypedContractEvent<
      WithdrawDogeEvent.InputTuple,
      WithdrawDogeEvent.OutputTuple,
      WithdrawDogeEvent.OutputObject
    >;
    WithdrawDoge: TypedContractEvent<
      WithdrawDogeEvent.InputTuple,
      WithdrawDogeEvent.OutputTuple,
      WithdrawDogeEvent.OutputObject
    >;
  };
}
