/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MixerPoolV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "FIELD_SIZE"
      | "MAX_DELAY"
      | "MIN_DELAY"
      | "ROOT_HISTORY_SIZE"
      | "TREE_DEPTH"
      | "commitments"
      | "currentRootIndex"
      | "denomination"
      | "deposit"
      | "executeScheduledWithdrawal"
      | "filledSubtrees"
      | "getLatestRoot"
      | "getPendingWithdrawal"
      | "getPoolInfo"
      | "getPoolInfoV2"
      | "getWithdrawalStatus"
      | "hasher"
      | "isDeposited"
      | "isKnownRoot"
      | "isSpent"
      | "nextLeafIndex"
      | "nullifierHashes"
      | "pendingWithdrawals"
      | "roots"
      | "scheduleWithdrawal"
      | "scheduledCount"
      | "token"
      | "verifier"
      | "withdraw"
      | "zeros"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposit"
      | "LeafInserted"
      | "Withdrawal"
      | "WithdrawalCancelled"
      | "WithdrawalExecuted"
      | "WithdrawalScheduled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FIELD_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_DELAY", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN_DELAY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ROOT_HISTORY_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREE_DEPTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commitments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentRootIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "denomination",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deposit", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "executeScheduledWithdrawal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "filledSubtrees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingWithdrawal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInfoV2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawalStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "hasher", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isDeposited",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isKnownRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isSpent", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "nextLeafIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nullifierHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingWithdrawals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "roots", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "scheduleWithdrawal",
    values: [
      BigNumberish[],
      BytesLike,
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduledCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [
      BigNumberish[],
      BytesLike,
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "zeros", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "FIELD_SIZE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAX_DELAY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_DELAY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ROOT_HISTORY_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "TREE_DEPTH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentRootIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "denomination",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeScheduledWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "filledSubtrees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInfoV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawalStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasher", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isKnownRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isSpent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextLeafIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nullifierHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roots", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "scheduleWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduledCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "zeros", data: BytesLike): Result;
}

export namespace DepositEvent {
  export type InputTuple = [
    commitment: BytesLike,
    leafIndex: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    commitment: string,
    leafIndex: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    commitment: string;
    leafIndex: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeafInsertedEvent {
  export type InputTuple = [
    leaf: BytesLike,
    leafIndex: BigNumberish,
    newRoot: BytesLike
  ];
  export type OutputTuple = [leaf: string, leafIndex: bigint, newRoot: string];
  export interface OutputObject {
    leaf: string;
    leafIndex: bigint;
    newRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    recipient: AddressLike,
    nullifierHash: BytesLike,
    relayer: AddressLike,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    recipient: string,
    nullifierHash: string,
    relayer: string,
    fee: bigint
  ];
  export interface OutputObject {
    recipient: string;
    nullifierHash: string;
    relayer: string;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalCancelledEvent {
  export type InputTuple = [nullifierHash: BytesLike, recipient: AddressLike];
  export type OutputTuple = [nullifierHash: string, recipient: string];
  export interface OutputObject {
    nullifierHash: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalExecutedEvent {
  export type InputTuple = [
    nullifierHash: BytesLike,
    recipient: AddressLike,
    executor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    nullifierHash: string,
    recipient: string,
    executor: string,
    amount: bigint
  ];
  export interface OutputObject {
    nullifierHash: string;
    recipient: string;
    executor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalScheduledEvent {
  export type InputTuple = [
    nullifierHash: BytesLike,
    recipient: AddressLike,
    unlockTime: BigNumberish,
    delay: BigNumberish
  ];
  export type OutputTuple = [
    nullifierHash: string,
    recipient: string,
    unlockTime: bigint,
    delay: bigint
  ];
  export interface OutputObject {
    nullifierHash: string;
    recipient: string;
    unlockTime: bigint;
    delay: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MixerPoolV2 extends BaseContract {
  connect(runner?: ContractRunner | null): MixerPoolV2;
  waitForDeployment(): Promise<this>;

  interface: MixerPoolV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FIELD_SIZE: TypedContractMethod<[], [bigint], "view">;

  MAX_DELAY: TypedContractMethod<[], [bigint], "view">;

  MIN_DELAY: TypedContractMethod<[], [bigint], "view">;

  ROOT_HISTORY_SIZE: TypedContractMethod<[], [bigint], "view">;

  TREE_DEPTH: TypedContractMethod<[], [bigint], "view">;

  commitments: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  currentRootIndex: TypedContractMethod<[], [bigint], "view">;

  denomination: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<[commitment: BytesLike], [void], "nonpayable">;

  executeScheduledWithdrawal: TypedContractMethod<
    [nullifierHash: BytesLike],
    [void],
    "nonpayable"
  >;

  filledSubtrees: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getLatestRoot: TypedContractMethod<[], [string], "view">;

  getPendingWithdrawal: TypedContractMethod<
    [nullifierHash: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        recipient: string;
        relayer: string;
        fee: bigint;
        unlockTime: bigint;
        executed: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  getPoolInfo: TypedContractMethod<
    [],
    [
      [string, bigint, bigint, string] & {
        _token: string;
        _denomination: bigint;
        _depositsCount: bigint;
        _root: string;
      }
    ],
    "view"
  >;

  getPoolInfoV2: TypedContractMethod<
    [],
    [
      [string, bigint, bigint, bigint, string, bigint, bigint] & {
        _token: string;
        _denomination: bigint;
        _depositsCount: bigint;
        _scheduledCount: bigint;
        _root: string;
        _minDelay: bigint;
        _maxDelay: bigint;
      }
    ],
    "view"
  >;

  getWithdrawalStatus: TypedContractMethod<
    [nullifierHash: BytesLike],
    [
      [bigint, bigint, boolean, boolean] & {
        timeRemaining: bigint;
        unlockTime: bigint;
        isReady: boolean;
        executed: boolean;
      }
    ],
    "view"
  >;

  hasher: TypedContractMethod<[], [string], "view">;

  isDeposited: TypedContractMethod<[commitment: BytesLike], [boolean], "view">;

  isKnownRoot: TypedContractMethod<[root: BytesLike], [boolean], "view">;

  isSpent: TypedContractMethod<[nullifierHash: BytesLike], [boolean], "view">;

  nextLeafIndex: TypedContractMethod<[], [bigint], "view">;

  nullifierHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  pendingWithdrawals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        recipient: string;
        relayer: string;
        fee: bigint;
        unlockTime: bigint;
        executed: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  roots: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  scheduleWithdrawal: TypedContractMethod<
    [
      proof: BigNumberish[],
      root: BytesLike,
      nullifierHash: BytesLike,
      recipient: AddressLike,
      relayer: AddressLike,
      fee: BigNumberish,
      delay: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  scheduledCount: TypedContractMethod<[], [bigint], "view">;

  token: TypedContractMethod<[], [string], "view">;

  verifier: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<
    [
      proof: BigNumberish[],
      root: BytesLike,
      nullifierHash: BytesLike,
      recipient: AddressLike,
      relayer: AddressLike,
      fee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  zeros: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FIELD_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROOT_HISTORY_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TREE_DEPTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "commitments"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "currentRootIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "denomination"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[commitment: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeScheduledWithdrawal"
  ): TypedContractMethod<[nullifierHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "filledSubtrees"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getLatestRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPendingWithdrawal"
  ): TypedContractMethod<
    [nullifierHash: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        recipient: string;
        relayer: string;
        fee: bigint;
        unlockTime: bigint;
        executed: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolInfo"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, bigint, string] & {
        _token: string;
        _denomination: bigint;
        _depositsCount: bigint;
        _root: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolInfoV2"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, bigint, bigint, string, bigint, bigint] & {
        _token: string;
        _denomination: bigint;
        _depositsCount: bigint;
        _scheduledCount: bigint;
        _root: string;
        _minDelay: bigint;
        _maxDelay: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWithdrawalStatus"
  ): TypedContractMethod<
    [nullifierHash: BytesLike],
    [
      [bigint, bigint, boolean, boolean] & {
        timeRemaining: bigint;
        unlockTime: bigint;
        isReady: boolean;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasher"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isDeposited"
  ): TypedContractMethod<[commitment: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isKnownRoot"
  ): TypedContractMethod<[root: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSpent"
  ): TypedContractMethod<[nullifierHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextLeafIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nullifierHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingWithdrawals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        recipient: string;
        relayer: string;
        fee: bigint;
        unlockTime: bigint;
        executed: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "roots"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "scheduleWithdrawal"
  ): TypedContractMethod<
    [
      proof: BigNumberish[],
      root: BytesLike,
      nullifierHash: BytesLike,
      recipient: AddressLike,
      relayer: AddressLike,
      fee: BigNumberish,
      delay: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scheduledCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [
      proof: BigNumberish[],
      root: BytesLike,
      nullifierHash: BytesLike,
      recipient: AddressLike,
      relayer: AddressLike,
      fee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "zeros"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "LeafInserted"
  ): TypedContractEvent<
    LeafInsertedEvent.InputTuple,
    LeafInsertedEvent.OutputTuple,
    LeafInsertedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalCancelled"
  ): TypedContractEvent<
    WithdrawalCancelledEvent.InputTuple,
    WithdrawalCancelledEvent.OutputTuple,
    WithdrawalCancelledEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalExecuted"
  ): TypedContractEvent<
    WithdrawalExecutedEvent.InputTuple,
    WithdrawalExecutedEvent.OutputTuple,
    WithdrawalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalScheduled"
  ): TypedContractEvent<
    WithdrawalScheduledEvent.InputTuple,
    WithdrawalScheduledEvent.OutputTuple,
    WithdrawalScheduledEvent.OutputObject
  >;

  filters: {
    "Deposit(bytes32,uint256,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "LeafInserted(bytes32,uint256,bytes32)": TypedContractEvent<
      LeafInsertedEvent.InputTuple,
      LeafInsertedEvent.OutputTuple,
      LeafInsertedEvent.OutputObject
    >;
    LeafInserted: TypedContractEvent<
      LeafInsertedEvent.InputTuple,
      LeafInsertedEvent.OutputTuple,
      LeafInsertedEvent.OutputObject
    >;

    "Withdrawal(address,bytes32,address,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;

    "WithdrawalCancelled(bytes32,address)": TypedContractEvent<
      WithdrawalCancelledEvent.InputTuple,
      WithdrawalCancelledEvent.OutputTuple,
      WithdrawalCancelledEvent.OutputObject
    >;
    WithdrawalCancelled: TypedContractEvent<
      WithdrawalCancelledEvent.InputTuple,
      WithdrawalCancelledEvent.OutputTuple,
      WithdrawalCancelledEvent.OutputObject
    >;

    "WithdrawalExecuted(bytes32,address,address,uint256)": TypedContractEvent<
      WithdrawalExecutedEvent.InputTuple,
      WithdrawalExecutedEvent.OutputTuple,
      WithdrawalExecutedEvent.OutputObject
    >;
    WithdrawalExecuted: TypedContractEvent<
      WithdrawalExecutedEvent.InputTuple,
      WithdrawalExecutedEvent.OutputTuple,
      WithdrawalExecutedEvent.OutputObject
    >;

    "WithdrawalScheduled(bytes32,address,uint256,uint256)": TypedContractEvent<
      WithdrawalScheduledEvent.InputTuple,
      WithdrawalScheduledEvent.OutputTuple,
      WithdrawalScheduledEvent.OutputObject
    >;
    WithdrawalScheduled: TypedContractEvent<
      WithdrawalScheduledEvent.InputTuple,
      WithdrawalScheduledEvent.OutputTuple,
      WithdrawalScheduledEvent.OutputObject
    >;
  };
}
